version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - "../helper_db:/var/lib/postgresql/data"
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  docker-hoster:
    image: dvdarias/docker-hoster
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "/etc/hosts:/tmp/hosts"