version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  
  telegram_bot:
    build:
      context: ../telegram_bot/
      dockerfile: Dockerfile
    volumes: 
      - telegram-bot-data:/var/lib/telegram-bot-data
    env_file: 
      - ./.env
     
volumes:
  static_value:
  media_value:
  telegram-bot-data:
